title: hypernephelist
tagline: 'n. [from Greek nepho-, cloud] someone who goes above the clouds.'
description: 'A technical blog by Thomas Conté on cloud, devices, and everything in between.'
url: 'http://hypernephelist.com'

version: 1.0

paginate: 5

markdown: redcarpet
highlighter: pygments

gems:
  - jekyll-gist
  - jekyll-paginate
