title: hypernephelist
tagline: 'Thomas Conté, Azure Technical Evangelist, Microsoft'
description: 'A blog about cloud technologies maintained by Thomas Conté, Technical Evangelist at Microsoft.'
url: 'http://hypernephelist.com'

version: 0.1

paginate: 5

markdown: redcarpet
highlighter: pygments
