title: hypernephelist
tagline: 'to the cloud and beyond!'
description: 'A blog about cloud technologies maintained by Thomas Conte, Technical Evangelist at Microsoft.'
url: 'http://hypernephelist.com'

version: 0.1

paginate: 5

markdown: kramdown
highlighter: rouge
